### PR TITLE
Refactor dockerfile

### PR DESCRIPTION
**Pull request by HotThoughts**
Hello, I am learning PyTorch Lightning and Hydra and come across finding this repo. Really useful and great work!

I made some changes in Dockerfile so the changes on the host machine can reflect within the container. When developing/training a model, mounting the files into the container instead of copying is more convenient and time-saving as all the changes I made and all the generated logs will be saved in the host machine.

Do you think it worth merging to the `master` branch or should be added to the` dockerfiles` branch?

### CODE REVIEW

**Comment by ashleve** [comment]
@HotThoughts Thanks, this is useful addition!
We can merge this into master although I would prefer not adding .dockerignore to keep the template more minimalistic. It seems like there are already too many files and I don't want to add anything that's not very necessary.

**Comment by HotThoughts** [comment]
@ashleve Awesome. I deleted the `.dockerignore` file. We don't really need it. Let me know if there are other changes you think we should do.

**Comment by ashleve** [comment]
@HotThoughts Thanks! It's merged now.

Btw I will be probably refactoring the dockerfile in the near future as it currently doesn't really work as I intended. Something like the one from huggingface library should make more sense for mixed-precision training:
https://github.com/huggingface/transformers/blob/master/docker/transformers-gpu/Dockerfile

**Comment by HotThoughts** [comment]
Yeah I can see the benefits of using pure `pip` to set up the environment. Right now the image is quite big ~25.5 GB, and I think most of it comes from the double installation of PyTorch (one from the base image, one from conda).

**Comment by HotThoughts** [comment]
I just checked out the `[apex](https://github.com/NVIDIA/apex)` and found that the stable version of `apex` is built-in in NVIDIA Pytorch containers from NGC, e.g. `nvcr.io/nvidia/pytorch:21.05-py3`, the one we use in Dockerfile. 

```console
root@c2c62b7515b9:/workspace/project# pip list | grep apex
apex                             0.1
```
Note `apex` is not in conda venv. I have to deactivate conda venv. 

If you want to install the latest `apex`, we can also easily do it:

> NVIDIA Pytorch containers from NGC, which come with Apex preinstalled. To use the latest Amp API, you may need to pip uninstall apex then reinstall Apex using the Quick Start commands below.
> 
> https://github.com/NVIDIA/apex#requirements

**Comment by ashleve** [comment]
@HotThoughts Yess, you're right with all of that
that's why I recently thought it would be better to inherit from simple cuda container (instead of the nvidia pytorch) and install everything from scratch (apex included), like they do in huggingface dockerfle

Although sorry I'm currently too busy with some deadlines to take care of that and prepare v1.0 of the template

**Pull request merged**
