### PR TITLE
Pytorch 2.0

### PR DESCRIPTION
**Pull request by johnnynunez**
New feature Pytorch 2.0 compile
Change pytorch-lightning(deprecated) to lightning
Pytorch 1.13.1 compatible with python 3.11
Only blocked tests torchvision but they are working to compatible with Python 3.11
Deleted Python 3.7 tests(very deprecated)

### CODE REVIEW

**Comment by ashleve** [comment]
Thank you for the PR @johnnynunez ! Could you consider splitting this into smaller, more atomic PRs?

Maybe a separate PR for renaming `pytorch_lightning` to `lightning`?

If I understand this correctly, pytorch 2.0 is currently in pre-release so I would prefer not to update the template until 2.0 is fully released.

> "Deleted Python 3.7 tests(very deprecated)" 

What do you mean by deprecated? In which library?

> "Only blocked tests torchvision but they are working to compatible with Python 3.11"

Does it mean torchvision doesn't work currently with Python 3.11?

**Comment by johnnynunez** [comment]
@ashleve thanks to response.
1. Maybe a separate PR for renaming pytorch_lightning to lightning?** 
Yes, I could do it.
2. If I understand this correctly, pytorch 2.0 is currently in pre-release so I would prefer not to update the template until 2.0 is fully released.
Yess, but Pytorch 1.13.1 has .compile because TorchDynamo  library now is in main repository.

3. What do you mean by deprecated? In which library?
I think that python 3.8 is the currently most useful because for example google colab it's on this version right now.

4. Does it mean torchvision doesn't work currently with Python 3.11?
TorchVision depends on anaconda repositories and not python version binary. So, anaconda is not still compatible with pytorch 3.11 but pytorch yes...

**Comment by ashleve** [comment]
@johnnynunez Sorry for delayed response, I was away for the past week.
1. Sure, you can go for it. 
I would like to make the development more organized so from now on let's make all PRs into the [dev](https://github.com/ashleve/lightning-hydra-template/tree/dev) branch and merge minor releases once in a while.

2. Ok, then we can already do a separate PR for `.compile()` feature

3. 3.7 is still officially supported by Python Foundation so I don't really see a reason to drop these tests unless some template dependency doesn't support it anymore.

4. For now, let's just not extend the list of tests to `3.11` until the issue with conda is fixed

**Comment by johnnynunez** [comment]
https://github.com/pytorch/vision/pull/7108 python 3.11
https://github.com/ContinuumIO/anaconda-issues/issues/13082#issuecomment-1386874942

**Comment by ashleve** [comment]
Deprecated python 3.7 with https://github.com/ashleve/lightning-hydra-template/pull/523

**Comment by johnnynunez** [comment]
@ashleve now is fixed in the last commit of master in lightning source

**Pull request closed without merging**
