### PR TITLE
Release 1.4.0

### PR DESCRIPTION
**Pull request by ashleve**

### CODE REVIEW

**Comment by zcx-language** [comment]
I think `pathlib` is better than `os.path`. Can we use the newer library instead of `os` in this template?

**Comment by ashleve** [comment]
> I think `pathlib` is better than `os.path`. Can we use the newer library instead of `os` in this template?

Good suggestion.

We can use `pathlib`, but I would still keep `os` in some cases where it seems cleaner, 

for example listing files in a directory:
```python
assert "last.ckpt" in os.listdir(tmp_path / "checkpoints")

# vs

path = Path(tmp_path, "checkpoints")
files = [str(file) for file in (path).iterdir()]
assert str(path / "last.ckpt") in files
```

**Comment by zcx-language** [comment]
OK，I see. Thanks for reply!

**Review by elisim — APPROVED** [review]

**Comment by ashleve** [comment]
Took longer than expected due to lack of time on my part, but the PR seems to be finished. 

I will merge it after experimenting a bit more with DPP.

**Pull request merged**
