### PR TITLE
Unified log dir structure

### PR DESCRIPTION
**Pull request by nils-werner**
This PR aims at unifying the log dir structure, to always follow

```
logs/{runs,multiruns}/$date/$time
logs/debug/{runs,multiruns}/$date/$time
logs/experiments/$experiment/{runs,multiruns}/$date/$time
```

before this PR, there was a mix of formats, e.g.

```
logs/runs/$date/$time
logs/multiruns/$date_$time
logs/debug/$date/$time
logs/debug/multiruns/$date_$time
logs/experiments/$experiment/$date_$time
logs/experiments/$experiment/multirun_$date_$time
```

and others.

Additionally, it introduces a little helper script `logs/latest` which can be used to quickly change into the latest log dir of a specific kind e.g.

```
cd $(logs/latest logs/runs)
cd $(logs/latest logs/multiruns)
```

### CODE REVIEW

**Comment by ashleve** [comment]
Sure, should have been like that from the beginning. Originally thought multiruns would end up having each job placed in different date-time folder, which made me go for less nested structure but now I realised Hydra doesn't work like this

**Comment by ashleve** [comment]
Are you sure the script is correct? seems like it doesn't work for my setup
image
Ubuntu 20.04

**Comment by nils-werner** [comment]
Oh right, `find` on macOS accepted the parameters, but on Linux they've changed. It should be working now, tested on both macOS and Linux.

**Comment by ashleve** [comment]
I modified the script to make it work even when the directory is not specified, please verify if works

**Review by ashleve — APPROVED** [review]

**Pull request merged**
